baseurl = "http://devhacks.github.io/"
languageCode = "en-us"
title = "Dev Hacks"

# Enable comments by entering your Disqus shortname
disqusShortname = "devhacks"
# Define the number of posts per site
paginate = 10
theme = "hugo-icarus-theme"


[permalinks]
    post = "/:year/:month/:day/:slug"


[params]
    # Tell me who you're
    author = "Ningsuhen Waikhom"
    bio = "Blogger - Programmer - Gopher"
    location = "Earth"
    site_description = ""
    copyright  = "Powered by [Hugo](//gohugo.io). Theme by [PPOffice](http://github.com/ppoffice)."

    # Enable Google Analytics by entering your tracking code
    google_analytics = ""

    # Format dates with Go's time formating
    date_format = "2006-01-02"

# Create custom menu entries by defining a label and a link for
# them. Since you can also link posts you've the option the
# place the links before or after them.
#
# E.g.: "Home" appears before all linked posts in the menu
# and "Tags" / "Categories" after them.
[[params.menu]]
    before = true
    label  = "Home"
    link   = "/"

[[params.menu]]
    before = false
    label  = "Tags"
    link   = "tags/"

[[params.menu]]
    before = false
    label  = "Categories"
    link   = "categories/"

[[params.menu]]
    before = false
    label  = "About"
    link   = "about"

# Enter a link for the follow button on the left
[params.profile]
    follow_button = "https://github.com/ningsuhen"


[params.social]
# Add your social network accounts to the profile section on the left
# by entering your username. The links to your account will be
# create automatically.
    github          = "ningsuhen"
    bitbucket       = "ningsuhen"
    jsfiddle        = ""
    codepen         = ""
    foursquare      = ""
    dribbble        = ""
    deviantart      = ""
    behance         = ""
    flickr          = ""
    instagram       = ""
    youtube         = "ningsuhen"
    vimeo           = "ningsuhen"
    vine            = ""
    medium          = ""
    wordpress       = ""
    tumblr          = ""
    xing            = ""
    linkedin        = "ningsuhen"
    slideshare      = ""
    stackoverflow   = "3478034/ningsuhen"
    reddit          = ""
    pinterest       = ""
    googleplus      = "" #WaikhomNingsuhen
    facebook        = "ningsuhen"
    facebook_admin  = ""
    twitter_domain  = ""
    twitter         = "ningsuhen"

# Enable and disable widgets for the right sidebar
[params.widgets]
    recent_articles = true
    categories = true
    tags = true
    tag_cloud = true
